### ISSUE TITLE
WO 174159 -- Fiber Updates

### ISSUE THREAD

**Issue by tnjtr2** [tnjtr2/TrafficEngineering#209]
- All Locations
   - [ ] Is the `Subtype` important for all the Fiber Termination points? What are they?
- Mineral Point Rd & D'Onofrio Dr / Randolph Rd
   - [x] Confusion about SW corner. Need to field check above ground assets to infer fiber (#179 
- Mineral Point Rd & Island Dr
   - [x] Check HH field checks on #222 
- Mineral Point Rd & Rosa Rd
   - [x] Any field checks on #223 
- Mineral Point Rd & Whitney Way
   - [x] Any field checks on #225 
- E Washington Ave & Livingston St
   - [x] Any changes to existing fiber? Two existing fibers already follow the path illustrated in as-built
- E Washington Ave & Baldwin St
   - [x] Any changes to existing fiber? One existing fiber already follows the path illustrated in as-built
- E Washington Ave & First St
   - [x] What path does the fiber crossing E Wash take in order to get to the splice case on the W corner?
- E Washington Ave & Mendota St
   - [x] What happened to the 12ct fiber crossing E Washington just NE of the intersection? This was a fiber added by Cory in 2020. Was it removed and a new cable pulled as shown in the as-built? Or was that previously existing cable relocated?

- E Washington Ave & Melvin Ct / Rethke Ave
   - [x] Reference WO 178205
-  E Washington Ave & Independence Ln
   - [x] Reference WO 178205
